// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: nexus_backend.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddServerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Chroot        string                 `protobuf:"bytes,2,opt,name=chroot,proto3" json:"chroot,omitempty"`
	SetS3Handler  bool                   `protobuf:"varint,3,opt,name=setS3Handler,proto3" json:"setS3Handler,omitempty"`
	SetRPCHandler bool                   `protobuf:"varint,4,opt,name=setRPCHandler,proto3" json:"setRPCHandler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerReq) Reset() {
	*x = AddServerReq{}
	mi := &file_nexus_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerReq) ProtoMessage() {}

func (x *AddServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerReq.ProtoReflect.Descriptor instead.
func (*AddServerReq) Descriptor() ([]byte, []int) {
	return file_nexus_backend_proto_rawDescGZIP(), []int{0}
}

func (x *AddServerReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddServerReq) GetChroot() string {
	if x != nil {
		return x.Chroot
	}
	return ""
}

func (x *AddServerReq) GetSetS3Handler() bool {
	if x != nil {
		return x.SetS3Handler
	}
	return false
}

func (x *AddServerReq) GetSetRPCHandler() bool {
	if x != nil {
		return x.SetRPCHandler
	}
	return false
}

type ServerMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VsockPath       string                 `protobuf:"bytes,2,opt,name=vsock_path,json=vsockPath,proto3" json:"vsock_path,omitempty"`
	RpcIncomingPort uint32                 `protobuf:"varint,3,opt,name=rpc_incoming_port,json=rpcIncomingPort,proto3" json:"rpc_incoming_port,omitempty"`
	S3Handler       bool                   `protobuf:"varint,4,opt,name=s3_handler,json=s3Handler,proto3" json:"s3_handler,omitempty"`
	RpcHandler      bool                   `protobuf:"varint,5,opt,name=rpc_handler,json=rpcHandler,proto3" json:"rpc_handler,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerMetadata) Reset() {
	*x = ServerMetadata{}
	mi := &file_nexus_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetadata) ProtoMessage() {}

func (x *ServerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetadata.ProtoReflect.Descriptor instead.
func (*ServerMetadata) Descriptor() ([]byte, []int) {
	return file_nexus_backend_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerMetadata) GetVsockPath() string {
	if x != nil {
		return x.VsockPath
	}
	return ""
}

func (x *ServerMetadata) GetRpcIncomingPort() uint32 {
	if x != nil {
		return x.RpcIncomingPort
	}
	return 0
}

func (x *ServerMetadata) GetS3Handler() bool {
	if x != nil {
		return x.S3Handler
	}
	return false
}

func (x *ServerMetadata) GetRpcHandler() bool {
	if x != nil {
		return x.RpcHandler
	}
	return false
}

type ListServersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*ServerMetadata      `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResp) Reset() {
	*x = ListServersResp{}
	mi := &file_nexus_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResp) ProtoMessage() {}

func (x *ListServersResp) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResp.ProtoReflect.Descriptor instead.
func (*ListServersResp) Descriptor() ([]byte, []int) {
	return file_nexus_backend_proto_rawDescGZIP(), []int{2}
}

func (x *ListServersResp) GetServers() []*ServerMetadata {
	if x != nil {
		return x.Servers
	}
	return nil
}

type GetServerMetadataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerMetadataReq) Reset() {
	*x = GetServerMetadataReq{}
	mi := &file_nexus_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerMetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerMetadataReq) ProtoMessage() {}

func (x *GetServerMetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerMetadataReq.ProtoReflect.Descriptor instead.
func (*GetServerMetadataReq) Descriptor() ([]byte, []int) {
	return file_nexus_backend_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerMetadataReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServerMetadataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerMetadataResp) Reset() {
	*x = GetServerMetadataResp{}
	mi := &file_nexus_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerMetadataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerMetadataResp) ProtoMessage() {}

func (x *GetServerMetadataResp) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerMetadataResp.ProtoReflect.Descriptor instead.
func (*GetServerMetadataResp) Descriptor() ([]byte, []int) {
	return file_nexus_backend_proto_rawDescGZIP(), []int{4}
}

func (x *GetServerMetadataResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveServerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerReq) Reset() {
	*x = RemoveServerReq{}
	mi := &file_nexus_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerReq) ProtoMessage() {}

func (x *RemoveServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerReq.ProtoReflect.Descriptor instead.
func (*RemoveServerReq) Descriptor() ([]byte, []int) {
	return file_nexus_backend_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveServerReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveServerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerResp) Reset() {
	*x = RemoveServerResp{}
	mi := &file_nexus_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerResp) ProtoMessage() {}

func (x *RemoveServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerResp.ProtoReflect.Descriptor instead.
func (*RemoveServerResp) Descriptor() ([]byte, []int) {
	return file_nexus_backend_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveServerResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DrainServerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainServerResp) Reset() {
	*x = DrainServerResp{}
	mi := &file_nexus_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainServerResp) ProtoMessage() {}

func (x *DrainServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainServerResp.ProtoReflect.Descriptor instead.
func (*DrainServerResp) Descriptor() ([]byte, []int) {
	return file_nexus_backend_proto_rawDescGZIP(), []int{7}
}

func (x *DrainServerResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_nexus_backend_proto protoreflect.FileDescriptor

const file_nexus_backend_proto_rawDesc = "" +
	"\n" +
	"\x13nexus_backend.proto\x12\x05proto\x1a\x15vm_orchestrator.proto\"\x80\x01\n" +
	"\fAddServerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06chroot\x18\x02 \x01(\tR\x06chroot\x12\"\n" +
	"\fsetS3Handler\x18\x03 \x01(\bR\fsetS3Handler\x12$\n" +
	"\rsetRPCHandler\x18\x04 \x01(\bR\rsetRPCHandler\"\xab\x01\n" +
	"\x0eServerMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"vsock_path\x18\x02 \x01(\tR\tvsockPath\x12*\n" +
	"\x11rpc_incoming_port\x18\x03 \x01(\rR\x0frpcIncomingPort\x12\x1d\n" +
	"\n" +
	"s3_handler\x18\x04 \x01(\bR\ts3Handler\x12\x1f\n" +
	"\vrpc_handler\x18\x05 \x01(\bR\n" +
	"rpcHandler\"B\n" +
	"\x0fListServersResp\x12/\n" +
	"\aservers\x18\x01 \x03(\v2\x15.proto.ServerMetadataR\aservers\"&\n" +
	"\x14GetServerMetadataReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15GetServerMetadataResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fRemoveServerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x10RemoveServerResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x0fDrainServerResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf9\x02\n" +
	"\fNexusBackend\x129\n" +
	"\tAddServer\x12\x13.proto.AddServerReq\x1a\x15.proto.ServerMetadata\"\x00\x12A\n" +
	"\fRemoveServer\x12\x16.proto.RemoveServerReq\x1a\x17.proto.RemoveServerResp\"\x00\x125\n" +
	"\vDrainServer\x12\f.proto.Empty\x1a\x16.proto.DrainServerResp\"\x00\x12P\n" +
	"\x11GetServerMetadata\x12\x1b.proto.GetServerMetadataReq\x1a\x1c.proto.GetServerMetadataResp\"\x00\x125\n" +
	"\vListServers\x12\f.proto.Empty\x1a\x16.proto.ListServersResp\"\x00\x12+\n" +
	"\x06GetPID\x12\f.proto.Empty\x1a\x11.proto.GetPIDResp\"\x00B+Z)github.com/JooyoungPark73/khala/pkg/protob\x06proto3"

var (
	file_nexus_backend_proto_rawDescOnce sync.Once
	file_nexus_backend_proto_rawDescData []byte
)

func file_nexus_backend_proto_rawDescGZIP() []byte {
	file_nexus_backend_proto_rawDescOnce.Do(func() {
		file_nexus_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_backend_proto_rawDesc), len(file_nexus_backend_proto_rawDesc)))
	})
	return file_nexus_backend_proto_rawDescData
}

var file_nexus_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nexus_backend_proto_goTypes = []any{
	(*AddServerReq)(nil),          // 0: proto.AddServerReq
	(*ServerMetadata)(nil),        // 1: proto.ServerMetadata
	(*ListServersResp)(nil),       // 2: proto.ListServersResp
	(*GetServerMetadataReq)(nil),  // 3: proto.GetServerMetadataReq
	(*GetServerMetadataResp)(nil), // 4: proto.GetServerMetadataResp
	(*RemoveServerReq)(nil),       // 5: proto.RemoveServerReq
	(*RemoveServerResp)(nil),      // 6: proto.RemoveServerResp
	(*DrainServerResp)(nil),       // 7: proto.DrainServerResp
	(*Empty)(nil),                 // 8: proto.Empty
	(*GetPIDResp)(nil),            // 9: proto.GetPIDResp
}
var file_nexus_backend_proto_depIdxs = []int32{
	1, // 0: proto.ListServersResp.servers:type_name -> proto.ServerMetadata
	0, // 1: proto.NexusBackend.AddServer:input_type -> proto.AddServerReq
	5, // 2: proto.NexusBackend.RemoveServer:input_type -> proto.RemoveServerReq
	8, // 3: proto.NexusBackend.DrainServer:input_type -> proto.Empty
	3, // 4: proto.NexusBackend.GetServerMetadata:input_type -> proto.GetServerMetadataReq
	8, // 5: proto.NexusBackend.ListServers:input_type -> proto.Empty
	8, // 6: proto.NexusBackend.GetPID:input_type -> proto.Empty
	1, // 7: proto.NexusBackend.AddServer:output_type -> proto.ServerMetadata
	6, // 8: proto.NexusBackend.RemoveServer:output_type -> proto.RemoveServerResp
	7, // 9: proto.NexusBackend.DrainServer:output_type -> proto.DrainServerResp
	4, // 10: proto.NexusBackend.GetServerMetadata:output_type -> proto.GetServerMetadataResp
	2, // 11: proto.NexusBackend.ListServers:output_type -> proto.ListServersResp
	9, // 12: proto.NexusBackend.GetPID:output_type -> proto.GetPIDResp
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nexus_backend_proto_init() }
func file_nexus_backend_proto_init() {
	if File_nexus_backend_proto != nil {
		return
	}
	file_vm_orchestrator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_backend_proto_rawDesc), len(file_nexus_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_backend_proto_goTypes,
		DependencyIndexes: file_nexus_backend_proto_depIdxs,
		MessageInfos:      file_nexus_backend_proto_msgTypes,
	}.Build()
	File_nexus_backend_proto = out.File
	file_nexus_backend_proto_goTypes = nil
	file_nexus_backend_proto_depIdxs = nil
}
